spring:
  # ---- DB ----
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    driverClassName: org.postgresql.Driver
    # DB_HOST:
    # 'localhost' for backend unlinked in docker-compose
    # 'db' for backend linked in docker-compose
    url: jdbc:postgresql://${DB_HOST:db}/${DB_NAME:mydb}
    username: ${DB_USER:myuser}
    password: ${DB_PASS:mypassword}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true # true for format the queries (requires show_sql to true)
        show_sql: true
    defer-datasource-initialization: true # load schema from entities
    show-sql: true # show sql queries formatted (true for formatted, requires spring.jpa.properties.hibernate.show_sql and spring.jpa.properties.hibernate.format_sql)
server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
