spring:
  # ---- DB ----
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${DB_START_MODE:none}
    properties:
      hibernate:
        format_sql: ${SHOW_SQL:false}
        show_sql: ${SHOW_SQL:false}
    defer-datasource-initialization: true
    show-sql: false
