application:
  title: '@project.name@'
  name: '@project.artifactId@'
  url: 'https://ipreach.app'
  version: '@project.version@'

spring:
  application:
    name: iPb

  # ---- PROFILE ----
  profiles:
    include:
      - ${ENVIRONMENT_PROFILE:local}
      - endpoints
      - swagger
      - security

  # ---- API ----
  mvc:
    servlet:
      path: /api/v1

  # ---- JSON MAPPER ----
  jackson:
    default-property-inclusion: non_null

# ---- SERVER ----
server:
  port: ${TOMCAT_PORT:8080}

# ---- COOKIES ----
  servlet:
    session:
      cookie:
        secure: ${COOKIES_SECURE:false}

# ---- LOGGING ----
logging:
  level:
    root: ${LOGGING_ROOT:INFO}
    org.springframework.web: ${LOGGING_SPRING_WEB:INFO}
    org.springframework.boot.autoconfigure.logging: ${LOGGING_SPRING_BOOT:INFO}
    app.ipreach.backend: ${LOGGING_API:INFO}
    org.hibernate.SQL: ${LOGGING_HIBERNATE:ERROR}
    org.hibernate.type.descriptor.sql: ${LOGGING_HIBERNATE:ERROR}
    org.hibernate.orm.jdbc.bind: ${LOGGING_HIBERNATE:ERROR}

refresh-token-header: x-refresh-token
payload-token-header: x-header-payload-token
signature-token-header: x-signature-token

